//
//  VipInteractor.swift
//  Teste Solutis-Santander
//
//  Created by Virtual Machine on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VipBusinessLogic
{
  func doSomething(request: Vip.Something.Request)
}

protocol VipDataStore
{
  //var name: String { get set }
}

class VipInteractor: VipBusinessLogic, VipDataStore
{
  var presenter: VipPresentationLogic?
  var worker: VipWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Vip.Something.Request)
  {
    worker = VipWorker()
    worker?.doSomeWork()
    
    let response = Vip.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
