//
//  VipPresenter.swift
//  Teste Solutis-Santander
//
//  Created by Virtual Machine on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VipPresentationLogic
{
  func presentSomething(response: Vip.Something.Response)
}

class VipPresenter: VipPresentationLogic
{
  weak var viewController: VipDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Vip.Something.Response)
  {
    let viewModel = Vip.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
