//
//  HomeInteractor.swift
//  Teste Solutis-Santander
//
//  Created by Virtual Machine on 23/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func showUserData(request: Home.UserData.Request)
    func showExtratos(request: Home.ExtratosData.Request)
    
}

protocol HomeDataStore
{
    var user: User? { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    var user: User?
    
    // MARK: Do something
    
    func showUserData(request: Home.UserData.Request)
    {
        let response = Home.UserData.Response(user: user!)
        presenter?.presentUserData(response: response)
    }
    
    func showExtratos(request: Home.ExtratosData.Request) {
        worker = HomeWorker()
        worker?.pegaExtratos(token: user!.token, completion: { listaExtratos in
            let response = Home.ExtratosData.Response(extrato: listaExtratos)
            self.presenter?.presentExtrato(response: response)
        })
    }
}
