//
//  HomeModels.swift
//  Teste Solutis-Santander
//
//  Created by Virtual Machine on 23/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
    // MARK: Use cases
    
    enum UserData
    {
        struct Request
        {
        }
        struct Response
        {
            let user: User
        }
        struct ViewModel
        {
            let user: User
        }
    }
    enum ExtratosData
    {
        struct Request
        {
        }
        struct Response
        {
            let extrato: Array<Extratos>
        }
        struct ViewModel
        {
            let extrato: Array<Extratos>
        }
    }
    
}
