//
//  HomePresenter.swift
//  Teste Solutis-Santander
//
//  Created by Virtual Machine on 23/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentUserData(response: Home.UserData.Response)
    func presentExtrato(response: Home.ExtratosData.Response)
}

class HomePresenter: HomePresentationLogic
{
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
    
    func presentUserData(response: Home.UserData.Response)
    {
        let viewModel = Home.UserData.ViewModel(user: response.user)
        viewController?.displayUserData(viewModel: viewModel)
    }
    
    func presentExtrato(response: Home.ExtratosData.Response) {
        
        let viewModel = Home.ExtratosData.ViewModel(extrato: response.extrato)
        viewController?.displayExtratos(viewModel: viewModel)
    }
}
