//
//  VipWorker.swift
//  Teste Solutis-Santander
//
//  Created by Virtual Machine on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
    private let api = API()
    
    func doLogin(username: String, password: String, completion: @escaping (_ usuario:User) -> Void) {
        api.login(username, password) { user in
            completion(user)
        }
        return
    }
}
 
