//
//  VipPresenter.swift
//  Teste Solutis-Santander
//
//  Created by Virtual Machine on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentHome(response: LoginModels.Login.Response)
    func presentError()
}

class LoginPresenter: LoginPresentationLogic
{
    weak var viewController: LoginDisplayLogic?
    
    // MARK: Do something
    
    func presentHome(response: LoginModels.Login.Response)
    {
        let viewModel = LoginModels.Login.ViewModel(user: response.user)
        viewController?.displayHome(viewModel: viewModel)
    }
    
    func presentError() {
        viewController?.displayError()
    }
}

