//
//  VipWorker.swift
//  Teste Solutis-Santander
//
//  Created by Virtual Machine on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SVProgressHUD

class LoginWorker
{
    private let api = API()
    let validator = Validation()
    func doLogin(username: String, password: String, completion: @escaping (_ usuario:User?) -> Void) {
        SVProgressHUD.show()
        if validator.validaTudo(username, password) {
            api.login(username, password) { (user) in
                if (self.api.succeeded == false) {
                    SVProgressHUD.dismiss()
                    completion(nil)
                    return
                    }
                else if self.api.succeeded == true {
                    SVProgressHUD.dismiss()
                    completion(user!)
                    }
                }
            }
            else {
                completion(nil)
                SVProgressHUD.dismiss()
                return
            }
        }
    }

 
