//
//  VipModels.swift
//  Teste Solutis-Santander
//
//  Created by Virtual Machine on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class LoginModels
{
  // MARK: Use cases
  
  enum Login
  {
    struct Request
    {
        var username: String
        var password: String
    }
    struct Response
    {
        var user: User
    }
    struct ViewModel
    {
        var user: User
    }
  }
    
    enum SavedUsername {
        struct Request {
            
        }
        
        struct Response {
            var username: String
        }
        
        struct ViewModel {
            var username: String
        }
        
    }
}
 
