//
//  VipInteractor.swift
//  Teste Solutis-Santander
//
//  Created by Virtual Machine on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import KeychainSwift

protocol LoginBusinessLogic
{
    func doLogin(request: LoginModels.Login.Request)
    func clearKeychain()
    func getKeychain()
}

protocol LoginDataStore
{
    var user: User? { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    var presenter: LoginPresentationLogic?
    var worker = LoginWorker()
    var user: User?
    
    // MARK: Do something
    
    func doLogin(request: LoginModels.Login.Request)
    {
        worker.doLogin(username: request.username, password: request.password, checked: request.checked, completion: { user in
            if let result = user {
                let response = LoginModels.Login.Response(user: result)
                self.user = result
                self.presenter?.presentHome(response: response)
            } else {
                self.presenter?.presentError()
            }
        })
    }
    
    func clearKeychain() {
        worker.clearKeychain()
    }
    
    func getKeychain() {
        presenter?.presentUser(username: worker.getKeychain())
    }
}

